cardArray = [ {id: 'card1', en: 'and', es: 'y', ga: 'agus', de: 'und', ru: 'а также', uk: 'і', fr: 'et', pl: 'i', tk: 'we', pt: 'e', ca: 'i' },
{id: 'card2', en: 'i', es: 'yo', ga: 'i', de: 'ich', ru: 'я', uk: 'я', fr: 'je', pl: 'ja', tk: 'men', pt: 'eu', ca: 'jo' },
{id: 'card3', en: 'that', es: 'ese', ga: 'go', de: 'das', ru: 'что', uk: 'що', fr: 'cette', pl: 'że', tk: 'şol', pt: 'aquele', ca: 'que' },
{id: 'card4', en: 'for', es: 'para', ga: 'do', de: 'zum', ru: 'за', uk: 'для', fr: 'pour', pl: 'dla', tk: 'üçin', pt: 'para', ca: 'per' },
{id: 'card5', en: 'you', es: 'tú', ga: 'tú', de: 'sie', ru: 'вы', uk: 'ви', fr: 'tu', pl: 'ty', tk: 'sen', pt: 'vocês', ca: 'vostè' },
{id: 'card6', en: 'he', es: 'él', ga: 'sé', de: 'er', ru: 'он', uk: 'він', fr: 'il', pl: 'on', tk: 'ol', pt: 'ele', ca: 'ell' },
{id: 'card7', en: 'with', es: 'con', ga: 'le', de: 'mit', ru: 'с участием', uk: 'з', fr: 'avec', pl: 'z', tk: 'bilen', pt: 'com', ca: 'amb' },
{id: 'card8', en: 'do', es: 'hacer', ga: 'dhéanamh', de: 'machen', ru: 'делать', uk: 'робити', fr: 'faire', pl: 'zrobić', tk: 'etmek', pt: 'faz', ca: 'fer' },
{id: 'card9', en: 'say', es: 'decir', ga: 'rá', de: 'sagen', ru: 'сказать', uk: 'сказати', fr: 'dire', pl: 'mówić', tk: 'diýmek', pt: 'dizer', ca: 'diguem' },
{id: 'card10', en: 'this', es: 'esta', ga: 'seo', de: 'dies', ru: 'этот', uk: 'це', fr: 'ce', pl: 'to', tk: 'bu', pt: 'esta', ca: 'aquest' },
{id: 'card11', en: 'they', es: 'ellos', ga: 'siad', de: 'sie', ru: 'oни', uk: 'вони', fr: 'ils', pl: 'one', tk: 'olar', pt: 'eles', ca: 'ells' },
{id: 'card12', en: 'we', es: 'nosotros', ga: 'táimid ag', de: 'wir', ru: 'мы', uk: 'ми', fr: 'nous', pl: 'my', tk: 'biz', pt: 'nós', ca: 'nosaltres' },
{id: 'card13', en: 'from', es: 'desde', ga: 'ó', de: 'von', ru: 'из', uk: 'від', fr: 'de', pl: 'z', tk: 'dan', pt: 'de', ca: 'de' },
{id: 'card14', en: 'not', es: 'no', ga: 'ní', de: 'nicht', ru: 'не', uk: 'не', fr: 'ne pas', pl: 'nie', tk: 'däl', pt: 'não', ca: 'no' },
{id: 'card15', en: 'by', es: 'por', ga: 'le', de: 'durch', ru: 'от', uk: 'по', fr: 'par', pl: 'przez', tk: 'tarapyndan', pt: 'por', ca: 'per' },
{id: 'card16', en: 'she', es: 'ella', ga: 'sí', de: 'sie', ru: 'она', uk: 'вона', fr: 'elle', pl: 'ona', tk: 'ol', pt: 'ela', ca: 'ella' },
{id: 'card17', en: 'what', es: 'qué', ga: 'cad', de: 'was', ru: 'какие', uk: 'що', fr: 'quoi', pl: 'co', tk: 'näme', pt: 'o que', ca: 'què' },
{id: 'card18', en: 'go', es: 'vamos', ga: 'dul', de: 'gehen', ru: 'идти', uk: 'йти', fr: 'aller', pl: 'udać się', tk: 'go', pt: 'vai', ca: 'go' },
{id: 'card19', en: 'can', es: 'lata', ga: 'is féidir', de: 'können', ru: 'может', uk: 'може', fr: 'pouvez', pl: 'mogą', tk: 'biler', pt: 'pode', ca: 'llauna' },
{id: 'card20', en: 'get', es: 'obtener', ga: 'fháil', de: 'erhalten', ru: 'получить', uk: 'прибудете', fr: 'avoir', pl: 'otrzymać', tk: 'bolsun', pt: 'pegue', ca: 'aconseguir' },
{id: 'card21', en: 'if', es: 'si', ga: 'dá', de: 'wenn', ru: 'если', uk: 'якщо', fr: 'si', pl: 'jeśli', tk: 'eger', pt: 'e se', ca: 'si' },
{id: 'card22', en: 'all', es: 'todas', ga: 'gach', de: 'alles', ru: 'все', uk: 'всі', fr: 'tout', pl: 'wszystko', tk: 'hemme', pt: 'todos', ca: 'tots' },
{id: 'card23', en: 'my', es: 'mi', ga: 'mo', de: 'meine', ru: 'мой', uk: 'мій', fr: 'mon', pl: 'mój', tk: 'meniň', pt: 'minha', ca: 'el meu' },
{id: 'card24', en: 'make', es: 'hacer', ga: 'déan', de: 'machen', ru: 'сделать', uk: 'макіяж', fr: 'faire', pl: 'robić', tk: 'make', pt: 'faço', ca: 'maquillatge' },
{id: 'card25', en: 'know', es: 'saber', ga: 'tá a fhios', de: 'kennt', ru: 'знать', uk: 'знати', fr: 'connaître', pl: 'wiedzieć', tk: 'bilmek', pt: 'conhecer', ca: 'conèixer' },
{id: 'card26', en: 'will', es: 'será', ga: 'beidh', de: 'werden', ru: 'воля', uk: 'волі', fr: 'volonté', pl: 'będzie', tk: 'bolar', pt: 'vai', ca: 'voluntat' },
{id: 'card27', en: 'up', es: 'arriba', ga: 'suas', de: 'oben', ru: 'вверх', uk: 'вгору', fr: 'en haut', pl: 'w górę', tk: 'ýokary', pt: 'acima', ca: 'fins' },
{id: 'card28', en: 'time', es: 'hora', ga: 'am', de: 'zeit', ru: 'время', uk: 'час', fr: 'temps', pl: 'czas', tk: 'wagt', pt: 'tempo', ca: 'temps' },
{id: 'card29', en: 'there', es: 'ahí', ga: 'ann', de: 'dort', ru: 'там', uk: 'там', fr: 'là', pl: 'tam', tk: 'ol ýerde', pt: 'há', ca: 'hi ha' },
{id: 'card30', en: 'year', es: 'año', ga: 'bhliain', de: 'jahr', ru: 'год', uk: 'рік', fr: 'an', pl: 'rok', tk: 'ýyl', pt: 'ano', ca: 'curs' },
{id: 'card31', en: 'so', es: 'entonces', ga: 'mar sin', de: 'damit', ru: 'так', uk: 'тому', fr: 'donc', pl: 'więc', tk: 'şeýle', pt: 'tão', ca: 'tan' },
{id: 'card32', en: 'think', es: 'pensar', ga: 'i mo thuairimse,', de: 'überlegen', ru: 'думать', uk: 'думати', fr: 'pense', pl: 'myśleć', tk: 'pikirlenmek', pt: 'pensar', ca: 'pensar' },
{id: 'card33', en: 'them', es: 'ellos', ga: 'iad', de: 'sie', ru: 'их', uk: 'їх', fr: 'leur', pl: 'im', tk: 'olary', pt: 'eles', ca: 'ells' },
{id: 'card34', en: 'me', es: 'yo', ga: 'me', de: 'mich', ru: 'мне', uk: 'мені', fr: 'moi', pl: 'mnie', tk: 'maňa', pt: 'mim', ca: 'em' },
{id: 'card35', en: 'people', es: 'personas', ga: 'daoine', de: 'menschen', ru: 'люди', uk: 'люди', fr: 'gens', pl: 'ludzie', tk: 'adamlar', pt: 'pessoas', ca: 'gent' },
{id: 'card36', en: 'take', es: 'tomar', ga: 'ghlacadh', de: 'nehmen', ru: 'принимать', uk: 'приймати', fr: 'prendre', pl: 'brać', tk: 'almak', pt: 'toma', ca: 'prendre' },
{id: 'card37', en: 'see', es: 'ver', ga: 'féach', de: 'sehen', ru: 'увидеть', uk: 'подивитися', fr: 'voir', pl: 'widzieć', tk: 'görmek', pt: 'vejo', ca: 'veure' },
{id: 'card38', en: 'your', es: 'tu', ga: 'do', de: 'ihre', ru: 'ваш', uk: 'ваш', fr: 'votre', pl: 'twój', tk: 'seniň', pt: 'seu', ca: 'seva' },
{id: 'card39', en: 'now', es: 'ahora', ga: 'anois', de: 'jetzt', ru: 'сейчас же', uk: 'в даний час', fr: 'maintenant', pl: 'teraz', tk: 'häzir', pt: 'agora', ca: 'ara' },
{id: 'card40', en: 'other', es: 'otro', ga: 'eile', de: 'andere', ru: 'другие', uk: 'інший', fr: 'autre', pl: 'inny', tk: 'beýleki', pt: 'de outros', ca: 'un altre' },
{id: 'card41', en: 'how', es: 'cómo', ga: 'conas', de: 'wie', ru: 'как', uk: 'як', fr: 'comment', pl: 'w jaki sposób', tk: 'nähili', pt: 'como', ca: 'com' },
{id: 'card42', en: 'then', es: 'entonces', ga: 'ansin', de: 'dann', ru: 'тогда', uk: 'тоді', fr: 'puis', pl: 'następnie', tk: 'onda', pt: 'então', ca: 'llavors' },
{id: 'card43', en: 'our', es: 'nuestra', ga: 'ár', de: 'unser', ru: 'наш', uk: 'наш', fr: 'notre', pl: 'nasz', tk: 'biziň', pt: 'nosso', ca: 'nostre' },
{id: 'card44', en: 'two', es: 'dos', ga: 'dhá', de: 'zwei', ru: 'два', uk: 'два', fr: 'deux', pl: 'dwa', tk: 'iki', pt: 'dois', ca: 'dos' },
{id: 'card45', en: 'more', es: 'más', ga: 'níos', de: 'mehr', ru: 'больше', uk: 'більше', fr: 'plus', pl: 'jeszcze', tk: 'has köp', pt: 'mais', ca: 'més' },
{id: 'card46', en: 'want', es: 'desear', ga: 'ag iarraidh', de: 'wollen', ru: 'хотеть', uk: 'хотіти', fr: 'vouloir', pl: 'chcieć', tk: 'isleýän', pt: 'quer', ca: 'voler' },
{id: 'card47', en: 'way', es: 'camino', ga: 'bhealach', de: 'weg', ru: 'путь', uk: 'шлях', fr: 'façon', pl: 'sposób', tk: 'ýol', pt: 'maneira', ca: 'camí' },
{id: 'card48', en: 'first', es: 'primero', ga: 'ar dtús', de: 'zuerst', ru: 'первый', uk: 'спочатку', fr: 'première', pl: 'pierwszy', tk: 'ilkinji', pt: 'primeiro', ca: 'primer' },
{id: 'card49', en: 'also', es: 'además', ga: 'chomh maith', de: 'ebenfalls', ru: 'также', uk: 'також', fr: 'aussi', pl: 'również', tk: 'hem', pt: 'além disso', ca: 'també' },
{id: 'card50', en: 'new', es: 'nuevo', ga: 'nua', de: 'neu', ru: 'новый', uk: 'новий', fr: 'nouveau', pl: 'nowy', tk: 'täze', pt: 'novo', ca: 'nou' },
{id: 'card51', en: 'because', es: 'porque', ga: 'mar', de: 'weil', ru: 'так как', uk: 'оскільки', fr: 'car', pl: 'dlatego', tk: 'sebäbi', pt: 'porque', ca: 'perquè' },
{id: 'card52', en: 'day', es: 'día', ga: 'lá', de: 'tag', ru: 'день', uk: 'день', fr: 'journée', pl: 'dzień', tk: 'gün', pt: 'dia', ca: 'dia' },
{id: 'card53', en: 'more', es: 'más', ga: 'níos', de: 'mehr', ru: 'больше', uk: 'більше', fr: 'plus', pl: 'jeszcze', tk: 'has köp', pt: 'mais', ca: 'més' },
{id: 'card54', en: 'use', es: 'utilizar', ga: 'úsáid', de: 'verwenden', ru: 'использование', uk: 'використання', fr: 'utilisation', pl: 'posługiwać się', tk: 'ulanmak', pt: 'usar', ca: 'ús' },
{id: 'card55', en: 'man', es: 'hombre', ga: 'fear', de: 'mann', ru: 'мужчина', uk: 'людина', fr: 'homme', pl: 'człowiek', tk: 'adam', pt: 'homem', ca: 'home' },
{id: 'card56', en: 'here', es: 'aquí', ga: 'anseo', de: 'hier', ru: 'вот', uk: 'тут', fr: 'ici', pl: 'tutaj', tk: 'bu ýerde', pt: 'aqui', ca: 'aquí' },
{id: 'card57', en: 'thing', es: 'cosa', ga: 'rud', de: 'ding', ru: 'вещь', uk: 'річ', fr: 'chose', pl: 'rzecz', tk: 'zat', pt: 'coisa', ca: 'cosa' },
{id: 'card58', en: 'give', es: 'dar', ga: 'a thabhairt', de: 'geben', ru: 'дать', uk: 'дати', fr: 'donner', pl: 'dać', tk: 'bermek', pt: 'dar', ca: 'donar' },
{id: 'card59', en: 'many', es: 'muchos', ga: 'go leor', de: 'viele', ru: 'многие', uk: 'багато', fr: 'beaucoup', pl: 'wiele', tk: 'köp', pt: 'muitos', ca: 'molts' },
{id: 'card60', en: 'tell', es: 'contar', ga: 'insint', de: 'sagen', ru: 'сказать', uk: 'сказати', fr: 'dire', pl: 'powiedzieć', tk: 'aýt', pt: 'contar', ca: 'dir' },
{id: 'card61', en: 'good', es: 'bueno', ga: 'maith', de: 'gut', ru: 'хороший', uk: 'добре', fr: 'bien', pl: 'dobry', tk: 'gowy', pt: 'boa', ca: 'bo' },
{id: 'card62', en: 'woman', es: 'mujer', ga: 'bean', de: 'frau', ru: 'женщина', uk: 'жінка', fr: 'femme', pl: 'kobieta', tk: 'aýal', pt: 'mulher', ca: 'dona' },
{id: 'card63', en: 'life', es: 'vida', ga: 'saol', de: 'leben', ru: 'жизнь', uk: 'життя', fr: 'la vie', pl: 'życie', tk: 'durmuş', pt: 'vida', ca: 'vida' },
{id: 'card64', en: 'child', es: 'niño', ga: 'leanbh', de: 'kind', ru: 'ребенок', uk: 'дитина', fr: 'enfant', pl: 'dziecko', tk: 'çaga', pt: 'criança', ca: 'nen' },
{id: 'card65', en: 'there', es: 'ahí', ga: 'ann', de: 'dort', ru: 'там', uk: 'там', fr: 'là', pl: 'tam', tk: 'ol ýerde', pt: 'há', ca: 'hi ha' },
{id: 'card66', en: 'work', es: 'trabajo', ga: 'obair', de: 'arbeit', ru: 'работа', uk: 'робота', fr: 'travail', pl: 'praca', tk: 'iş', pt: 'trabalhos', ca: 'treball' },
{id: 'card67', en: 'down', es: 'abajo', ga: 'síos', de: 'nieder', ru: 'вниз', uk: 'вниз', fr: 'vers le bas', pl: 'na dół', tk: 'aşak', pt: 'baixa', ca: 'baix' },
{id: 'card68', en: 'may', es: 'mayo', ga: 'féadfaidh', de: 'kann', ru: 'может', uk: 'може', fr: 'mai', pl: 'może', tk: 'biler', pt: 'maio', ca: 'pot' },
{id: 'card69', en: 'after', es: 'después', ga: 'tar éis', de: 'nach', ru: 'после', uk: 'після', fr: 'après', pl: 'po', tk: 'soň', pt: 'depois de', ca: 'després' },
{id: 'card70', en: 'call', es: 'llamada', ga: 'glaoch', de: 'anruf', ru: 'вызов', uk: 'виклик', fr: 'appel', pl: 'połączenie', tk: 'çagyryş', pt: 'ligar', ca: 'anomenada' },
{id: 'card71', en: 'world', es: 'mundo', ga: 'domhan', de: 'welt', ru: 'мир', uk: 'світ', fr: 'monde', pl: 'świat', tk: 'dünýä', pt: 'mundo', ca: 'món' },
{id: 'card72', en: 'school', es: 'colegio', ga: 'scoil', de: 'schule', ru: 'школа', uk: 'школу', fr: 'école', pl: 'szkoła', tk: 'mekdep', pt: 'escola', ca: 'escola' },
{id: 'card73', en: 'still', es: 'todavía', ga: 'fós', de: 'immer noch', ru: 'все еще', uk: 'ще', fr: 'encore', pl: 'nadal', tk: 'şonda-da', pt: 'ainda', ca: 'encara' },
{id: 'card74', en: 'try', es: 'tratar', ga: 'bain triail', de: 'versuchen', ru: 'пытаться', uk: 'пробувати', fr: 'essayer', pl: 'próbować', tk: 'görüň', pt: 'tentar', ca: 'intentar' },
{id: 'card75', en: 'ask', es: 'pedir', ga: 'a iarraidh', de: 'fragen', ru: 'просить', uk: 'запитати', fr: 'demander', pl: 'zapytać', tk: 'soramak', pt: 'perguntar', ca: 'preguntar' },
{id: 'card76', en: 'too', es: 'también', ga: 'freisin', de: 'zu', ru: 'слишком', uk: 'теж', fr: 'aussi', pl: 'też', tk: 'hem', pt: 'também', ca: 'massa' },
{id: 'card77', en: 'feel', es: 'sensación', ga: 'bhraitheann', de: 'gefühl', ru: 'чувствовать', uk: 'відчувати', fr: 'ressentir', pl: 'czuć', tk: 'duýup', pt: 'sentir', ca: 'sentir' },
{id: 'card78', en: 'when', es: 'cuando', ga: 'cathain', de: 'wann', ru: 'когда', uk: 'коли', fr: 'quand', pl: 'gdy', tk: 'wagty', pt: 'quando', ca: 'quan' },
{id: 'card79', en: 'between', es: 'entre', ga: 'idir', de: 'zwischen', ru: 'между', uk: 'між', fr: 'entre', pl: 'pomiędzy', tk: 'arasynda', pt: 'entre', ca: 'entre' },
{id: 'card80', en: 'high', es: 'alto', ga: 'ard', de: 'hoch', ru: 'высоко', uk: 'висока', fr: 'haute', pl: 'wysoki', tk: 'ýokary', pt: 'alto', ca: 'alt' },
{id: 'card81', en: 'really', es: 'de verdad', ga: 'i ndáiríre', de: 'ja wirklich', ru: 'действительно', uk: 'насправді', fr: 'vraiment', pl: 'naprawdę', tk: 'hakykatdan', pt: 'realmente', ca: 'realment' },
{id: 'card82', en: 'something', es: 'alguna cosa', ga: 'rud éigin', de: 'etwas', ru: 'что нибудь', uk: 'щось', fr: 'quelque chose', pl: 'coś', tk: 'zat', pt: 'alguma coisa', ca: 'alguna cosa' },
{id: 'card83', en: 'another', es: 'otro', ga: 'eile', de: 'ein weiterer', ru: 'еще один', uk: 'інший', fr: 'un autre', pl: 'inne', tk: 'başga bir', pt: 'outro', ca: 'un altre' },
{id: 'card84', en: 'put', es: 'poner', ga: 'chur', de: 'stellen', ru: 'ставить', uk: 'ставити', fr: 'mettre', pl: 'położyć', tk: 'goýdy', pt: 'colocar', ca: 'posar' },
{id: 'card85', en: 'old', es: 'antiguo', ga: 'sean', de: 'alt', ru: 'старый', uk: 'старий', fr: 'vieux', pl: 'stary', tk: 'köne', pt: 'velho', ca: 'vell' },
{id: 'card86', en: 'keep', es: 'mantener', ga: 'choinneáil', de: 'behalten', ru: 'хранить', uk: 'тримати', fr: 'garder', pl: 'trzymać', tk: 'tutmak', pt: 'manter', ca: 'mantenir' },
{id: 'card87', en: 'student', es: 'estudiante', ga: 'dalta', de: 'schüler', ru: 'студент', uk: 'студент', fr: 'étudiant', pl: 'student', tk: 'talyp', pt: 'aluna', ca: 'estudiant' },
{id: 'card88', en: 'why', es: 'por qué', ga: 'cén fáth', de: 'warum', ru: 'зачем', uk: 'чому', fr: 'pourquoi', pl: 'czemu', tk: 'üçin', pt: 'porque', ca: 'per què' },
{id: 'card89', en: 'let', es: 'dejar', ga: 'a ligean', de: 'lassen', ru: 'позволять', uk: 'дозволяє', fr: 'laisser', pl: 'pozwolić', tk: 'rugsat bermek', pt: 'deixei', ca: 'deixar' },
{id: 'card90', en: 'great', es: 'estupendo', ga: 'mór', de: 'groß', ru: 'большой', uk: 'великий', fr: 'génial', pl: 'świetny', tk: 'beýik', pt: 'ótimo', ca: 'gran' },
{id: 'card91', en: 'same', es: 'mismo', ga: 'céanna', de: 'gleich', ru: 'тем же', uk: 'то ж', fr: 'même', pl: 'podobnie', tk: 'şol bir', pt: 'mesmo', ca: 'mateix' },
{id: 'card92', en: 'group', es: 'grupo', ga: 'grúpa', de: 'gruppe', ru: 'группа', uk: 'група', fr: 'groupe', pl: 'grupa', tk: 'topar', pt: 'grupo', ca: 'grup' },
{id: 'card93', en: 'seem', es: 'parecer', ga: 'is cosúil', de: 'scheinen', ru: 'казаться', uk: 'здаватися', fr: 'sembler', pl: 'wydać się', tk: 'görünmek', pt: 'parecer', ca: 'semblar' },
{id: 'card94', en: 'country', es: 'país', ga: 'tír', de: 'land', ru: 'страна', uk: 'країна', fr: 'pays', pl: 'kraj', tk: 'ýurt', pt: 'país', ca: 'país' },
{id: 'card95', en: 'help', es: 'ayuda', ga: 'cabhrú', de: 'hilfe', ru: 'помогите', uk: 'допомога', fr: 'aidez-moi', pl: 'wsparcie', tk: 'kömek ediň', pt: 'socorro', ca: 'ajuda' },
{id: 'card96', en: 'talk', es: 'hablar', ga: 'labhairt', de: 'sich unterhalten', ru: 'разговаривать', uk: 'говорити', fr: 'parler', pl: 'rozmowa', tk: 'gürrüň', pt: 'falar', ca: 'parlar' },
{id: 'card97', en: 'turn', es: 'giro', ga: 'cas', de: 'wende', ru: 'поворот', uk: 'включити', fr: 'tour', pl: 'skręcać', tk: 'öçürmek', pt: 'virar', ca: 'giri' },
{id: 'card98', en: 'problem', es: 'problema', ga: 'fadhb', de: 'problem', ru: 'проблема', uk: 'проблема', fr: 'problème', pl: 'problem', tk: 'mesele', pt: 'problema', ca: 'problema' },
{id: 'card99', en: 'every', es: 'cada', ga: 'gach', de: 'jeder', ru: 'каждый', uk: 'кожен', fr: 'chaque', pl: 'każdy', tk: 'her', pt: 'cada', ca: 'cada' },
{id: 'card100', en: 'start', es: 'comienzo', ga: 'tús', de: 'start', ru: 'начало', uk: 'початок', fr: 'début', pl: 'początek', tk: 'başlangyç', pt: 'começar', ca: 'començar' },
{id: 'card101', en: 'hand', es: 'mano', ga: 'lámh', de: 'hand', ru: 'рука', uk: 'рука', fr: 'main', pl: 'dłoń', tk: 'el', pt: 'mão', ca: 'mà' },
{id: 'card102', en: 'show', es: 'show', ga: 'taispeáin', de: 'show', ru: 'шоу', uk: 'шоу', fr: 'montrer', pl: 'pokazać', tk: 'görkezmek', pt: 'mostrar', ca: 'espectacle' },
{id: 'card103', en: 'part', es: 'parte', ga: 'cuid', de: 'teil', ru: 'часть', uk: 'частина', fr: 'partie', pl: 'część', tk: 'bölegi', pt: 'parte', ca: 'part' },
{id: 'card104', en: 'against', es: 'en contra', ga: 'in aghaidh', de: 'gegen', ru: 'против', uk: 'проти', fr: 'contre', pl: 'przeciwko', tk: 'garşysynda', pt: 'contra', ca: 'contra' },
{id: 'card105', en: 'place', es: 'sitio', ga: 'áit', de: 'ort', ru: 'место', uk: 'місце', fr: 'endroit', pl: 'miejsce', tk: 'ýer', pt: 'lugar, colocar', ca: 'lloc' },
{id: 'card106', en: 'again', es: 'de nuevo', ga: 'arís', de: 'nochmal', ru: 'еще раз', uk: 'знову', fr: 'encore', pl: 'jeszcze raz', tk: 'ýene', pt: 'novamente', ca: 'de nou' },
{id: 'card107', en: 'case', es: 'caso', ga: 'cás', de: 'fall', ru: 'кейс', uk: 'випадок', fr: 'cas', pl: 'walizka', tk: 'guty', pt: 'caso', ca: 'caixa' },
{id: 'card108', en: 'week', es: 'semana', ga: 'seachtain', de: 'woche', ru: 'неделя', uk: 'тиждень', fr: 'la semaine', pl: 'tydzień', tk: 'hepde', pt: 'semana', ca: 'setmana' },
{id: 'card109', en: 'system', es: 'sistema', ga: 'córas', de: 'system', ru: 'система', uk: 'система', fr: 'système', pl: 'system', tk: 'ulgam', pt: 'sistema', ca: 'sistema' },
{id: 'card110', en: 'right', es: 'correcto', ga: 'ceart', de: 'richtig', ru: 'верно', uk: 'право', fr: 'droite', pl: 'dobrze', tk: 'dogry', pt: 'direito', ca: 'dret' },
{id: 'card111', en: 'program', es: 'programa', ga: 'clár', de: 'programm', ru: 'программа', uk: 'програма', fr: 'programme', pl: 'program', tk: 'programma', pt: 'programa', ca: 'programa' },
{id: 'card112', en: 'hear', es: 'oír', ga: 'chloisteáil', de: 'hören', ru: 'заслушивать', uk: 'заслуховувати', fr: 'entendre', pl: 'słyszeć', tk: 'eşitmek', pt: 'ouvir', ca: 'escoltar' },
{id: 'card113', en: 'so', es: 'entonces', ga: 'mar sin', de: 'damit', ru: 'так', uk: 'тому', fr: 'donc', pl: 'więc', tk: 'şeýle', pt: 'tão', ca: 'tan' },
{id: 'card114', en: 'question', es: 'pregunta', ga: 'ceist', de: 'frage', ru: 'вопрос', uk: 'питання', fr: 'question', pl: 'pytanie', tk: 'sorag', pt: 'questão', ca: 'pregunta' },
{id: 'card115', en: 'during', es: 'durante', ga: 'le linn', de: 'während', ru: 'в течение', uk: 'під час', fr: 'pendant', pl: 'podczas', tk: 'dowamynda', pt: 'durante', ca: 'durant' },
{id: 'card116', en: 'work', es: 'trabajo', ga: 'obair', de: 'arbeit', ru: 'работа', uk: 'робота', fr: 'travail', pl: 'praca', tk: 'iş', pt: 'trabalhos', ca: 'treball' },
{id: 'card117', en: 'play', es: 'tocar', ga: 'imirt', de: 'abspielen', ru: 'играть', uk: 'гра', fr: 'jouer', pl: 'grać', tk: 'oýun', pt: 'toque', ca: 'jugar' },
{id: 'card118', en: 'government', es: 'gobierno', ga: 'rialtas', de: 'regierung', ru: 'правительство', uk: 'уряд', fr: 'gouvernement', pl: 'rząd', tk: 'hökümet', pt: 'governo', ca: 'govern' },
{id: 'card119', en: 'small', es: 'pequeño', ga: 'beag', de: 'klein', ru: 'маленький', uk: 'маленький', fr: 'petit', pl: 'mały', tk: 'kiçi', pt: 'pequeno', ca: 'petit' },
{id: 'card120', en: 'number', es: 'número', ga: 'uimhir', de: 'nummer', ru: 'число', uk: 'номер', fr: 'nombre', pl: 'numer', tk: 'san', pt: 'número', ca: 'nombre' },
{id: 'card121', en: 'always', es: 'siempre', ga: 'i gcónaí', de: 'immer', ru: 'всегда', uk: 'завжди', fr: 'toujours', pl: 'zawsze', tk: 'hemişe', pt: 'sempre', ca: 'sempre' },
{id: 'card122', en: 'move', es: 'moverse', ga: 'bogadh', de: 'bewegung', ru: 'переехать', uk: 'рух', fr: 'bouge toi', pl: 'ruszaj się', tk: 'hereket etmek', pt: 'mover', ca: 'moviment' },
{id: 'card123', en: 'night', es: 'noche', ga: 'oíche', de: 'nacht-', ru: 'ночь', uk: 'ніч', fr: 'nuit', pl: 'noc', tk: 'gije', pt: 'noite', ca: 'nit' },
{id: 'card124', en: 'live', es: 'en vivo', ga: 'beo', de: 'leben', ru: 'прямой эфир', uk: 'в прямому ефірі', fr: 'vivre', pl: 'relacja na żywo', tk: 'janly', pt: 'viver', ca: 'en viu' },
{id: 'card125', en: 'mr.', es: 'señor.', ga: 'an tuasal.', de: 'herr.', ru: 'мистер.', uk: 'містер.', fr: 'monsieur.', pl: 'pan.', tk: 'jenap', pt: 'sr..', ca: 'sr.' },
{id: 'card126', en: 'point', es: 'punto', ga: 'pointe', de: 'punkt', ru: 'точка', uk: 'точка', fr: 'point', pl: 'punkt', tk: 'nokat', pt: 'ponto', ca: 'punt' },
{id: 'card127', en: 'believe', es: 'creer', ga: 'creidim', de: 'glauben', ru: 'верить', uk: 'вірити', fr: 'croyez', pl: 'uwierzyć', tk: 'ynanmak', pt: 'acreditam', ca: 'creure' },
{id: 'card128', en: 'happen', es: 'suceder', ga: 'a tharlóidh', de: 'geschehen', ru: 'случаться', uk: 'траплятися', fr: 'se produire', pl: 'zdarzyć', tk: 'bolup', pt: 'acontecer', ca: 'succeir' },
{id: 'card129', en: 'without', es: 'sin', ga: 'gan', de: 'ohne', ru: 'без', uk: 'без', fr: 'sans pour autant', pl: 'bez', tk: 'bolmazdan', pt: 'sem', ca: 'sense' },
{id: 'card130', en: 'before', es: 'antes de', ga: 'roimh', de: 'vor', ru: 'перед', uk: 'перед тим', fr: 'avant', pl: 'przed', tk: 'öň', pt: 'antes', ca: 'abans' },
{id: 'card131', en: 'all', es: 'todas', ga: 'gach', de: 'alles', ru: 'все', uk: 'всі', fr: 'tout', pl: 'wszystko', tk: 'hemme', pt: 'todos', ca: 'tots' },
{id: 'card132', en: 'million', es: 'millón', ga: 'milliún', de: 'million', ru: 'миллиона', uk: 'мільйона', fr: 'million', pl: 'milion', tk: 'million', pt: 'milhão', ca: 'milió' },
{id: 'card133', en: 'home', es: 'hogar', ga: 'baile', de: 'zuhause', ru: 'дом', uk: 'будинки', fr: 'domicile', pl: 'dom', tk: 'öý', pt: 'casa', ca: 'casa' },
{id: 'card134', en: 'under', es: 'debajo', ga: 'faoi', de: 'unter', ru: 'под', uk: 'під', fr: 'sous', pl: 'pod', tk: 'astynda', pt: 'sob', ca: 'sota' },
{id: 'card135', en: 'water', es: 'agua', ga: 'uisce', de: 'wasser', ru: 'вода', uk: 'вода', fr: 'eau', pl: 'woda', tk: 'suw', pt: 'água', ca: 'aigua' },
{id: 'card136', en: 'room', es: 'habitación', ga: 'seomra', de: 'zimmer', ru: 'комната', uk: 'кімната', fr: 'chambre', pl: 'pokój', tk: 'otag', pt: 'quarto', ca: 'habitació' },
{id: 'card137', en: 'write', es: 'escribir', ga: 'scríobh', de: 'schreiben', ru: 'записывать', uk: 'запис', fr: 'écrire', pl: 'pisać', tk: 'ýazmak', pt: 'escrever', ca: 'escriptura' },
{id: 'card138', en: 'mother', es: 'madre', ga: 'máthair', de: 'mutter', ru: 'мать', uk: 'мати', fr: 'mère', pl: 'matka', tk: 'ene', pt: 'mãe', ca: 'mare' },
{id: 'card139', en: 'area', es: 'zona', ga: 'limistéar', de: 'bereich', ru: 'площадь', uk: 'область', fr: 'surface', pl: 'powierzchnia', tk: 'meýdan', pt: 'área', ca: 'àrea' },
{id: 'card140', en: 'national', es: 'nacional', ga: 'náisiúnta', de: 'national', ru: 'национальный', uk: 'національний', fr: 'nationale', pl: 'krajowy', tk: 'milli', pt: 'nacional', ca: 'nacional' },
{id: 'card141', en: 'money', es: 'dinero', ga: 'airgead', de: 'geld', ru: 'деньги', uk: 'гроші', fr: 'argent', pl: 'pieniądze', tk: 'pul', pt: 'dinheiro', ca: 'diners' },
{id: 'card142', en: 'story', es: 'historia', ga: 'scéal', de: 'geschichte', ru: 'история', uk: 'история', fr: 'récit', pl: 'fabuła', tk: 'story', pt: 'história', ca: 'història' },
{id: 'card143', en: 'young', es: 'joven', ga: 'óg', de: 'jung', ru: 'молодой', uk: 'молодий', fr: 'jeune', pl: 'młody', tk: 'ýaş', pt: 'jovem', ca: 'jove' },
{id: 'card144', en: 'month', es: 'mes', ga: 'mí', de: 'monat', ru: 'месяц', uk: 'місяць', fr: 'mois', pl: 'miesiąc', tk: 'aý', pt: 'mês', ca: 'mes' },
{id: 'card145', en: 'different', es: 'diferente', ga: 'difriúil', de: 'anders', ru: 'разные', uk: 'інший', fr: 'différent', pl: 'różne', tk: 'dürli', pt: 'diferente', ca: 'diferent' },
{id: 'card146', en: 'right', es: 'correcto', ga: 'ceart', de: 'richtig', ru: 'верно', uk: 'право', fr: 'droite', pl: 'dobrze', tk: 'dogry', pt: 'direito', ca: 'dret' },
{id: 'card147', en: 'study', es: 'estudiar', ga: 'staidéar', de: 'studie', ru: 'исследование', uk: 'вивчення', fr: 'étude', pl: 'nauka', tk: 'iş', pt: 'estude', ca: 'estudiar' },
{id: 'card148', en: 'book', es: 'libro', ga: 'leabhar', de: 'buch', ru: 'книга', uk: 'книга', fr: 'livre', pl: 'książka', tk: 'kitap', pt: 'livro', ca: 'llibre' },
{id: 'card149', en: 'eye', es: 'ojo', ga: 'súil', de: 'auge', ru: 'глаз', uk: 'очей', fr: 'œil', pl: 'oko', tk: 'göz', pt: 'olho', ca: 'ull' },
{id: 'card150', en: 'job', es: 'trabajo', ga: 'post', de: 'job', ru: 'работа', uk: 'робота', fr: 'emploi', pl: 'praca', tk: 'iş', pt: 'trabalho', ca: 'treball' },
{id: 'card151', en: 'word', es: 'palabra', ga: 'focal', de: 'wort', ru: 'слово', uk: 'слово', fr: 'mot', pl: 'słowo', tk: 'söz', pt: 'palavra', ca: 'paraula' },
{id: 'card152', en: 'business', es: 'negocio', ga: 'gnó', de: 'unternehmen', ru: 'бизнес', uk: 'бізнес', fr: 'entreprise', pl: 'biznes', tk: 'iş', pt: 'o negócio', ca: 'negocis' },
{id: 'card153', en: 'side', es: 'lado', ga: 'taobh', de: 'seite', ru: 'боковая сторона', uk: 'сторона', fr: 'côté', pl: 'bok', tk: 'tarapy', pt: 'lado', ca: 'costat' },]

const TFList = [true,false,true,false,true,false,true,false,true,false]

oneToTwenty = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]